"""Update TenantMembership for invitations

Revision ID: b607e32bd100
Revises: c7c8c382dfc1
Create Date: 2026-01-31 06:40:42.833719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'b607e32bd100'
down_revision: Union[str, Sequence[str], None] = 'c7c8c382dfc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenantmembership', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invitee_email_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenantmembership', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('invitee_email_address')
    # ### end Alembic commands ###
