[request_definition]
r = user, org, module, action

[policy_definition]
p = role, org, module, action

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.user, p.role, r.org) &&
    r.org == p.org &&
    r.module == p.module &&
    r.action == p.action